[tool.poetry]
name = "lms-ds-loader"
version = "0.1.0"
description = ""
authors = ["Ed-Fi Alliance, LLC and contributors"]

[tool.poetry.dependencies]
python = "^3.8"
pyodbc = "^4.0.30"
sqlalchemy = "^1.3.19"
pandas = "^1.1.2"
configargparse = "^1.2.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
